name: action workflow

on: [push]

jobs:
  run-js-action:
    runs-on: ubuntu-latest
    steps:
      - name: hello world
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Sayantan
      - name: log time
        run: echo "${{ steps.greet.outputs.time }}"
      - name: checkout
        uses: actions/checkout@v2
      - name: print env variables
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
